import 'category_model.dart';
import 'recipe_model.dart';

final List<CategoryModel> categories = [


  ///===========================================>>>> BREAkFAST FOOD

  CategoryModel(
    title: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    recipes: [
      RecipeModel(
        name: 'Paratha with Aloo Sabzi',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 350,
        description: 'A flaky, buttery paratha served with spiced potato curry, a classic Pakistani breakfast.',
        ingredients: [
          '2 cups whole wheat flour',
          '1 cup boiled potatoes',
          '1 tsp cumin seeds',
          '1 tbsp ghee',
          'Salt to taste',
          '1/2 tsp turmeric',
        ],
        steps: [
          'Knead flour with water and salt to make dough, rest for 20 minutes.',
          'Mash potatoes with cumin, turmeric, and salt for sabzi.',
          'Roll dough into parathas, cook with ghee on a tawa until golden.',
          'Serve hot with aloo sabzi.',
        ],
        healthInfo: 'Calories: 350 kcal\nHealth Benefits:\n- Rich in carbs for energy.\n- High in fiber from whole wheat.\n- Supports digestion with spices.',
        time: '30 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Halwa Puri',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 400,
        description: 'A traditional Pakistani breakfast with crispy puris and sweet semolina halwa.',
        ingredients: [
          '1 cup semolina',
          '2 cups flour',
          '1/2 cup sugar',
          '2 tbsp ghee',
          '1/4 cup water',
          'Chickpeas curry (optional)',
        ],
        steps: [
          'Cook semolina with ghee, sugar, and water to make halwa.',
          'Knead flour into dough, roll into puris, and fry until puffed.',
          'Serve halwa with puris and chickpeas curry.',
        ],
        healthInfo: 'Calories: 400 kcal\nHealth Benefits:\n- Provides quick energy from carbs.\n- Rich in iron from semolina.\n- Balanced with protein from curry.',
        time: '25 min',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Nihari with Naan',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 450,
        description: 'A rich, slow-cooked beef stew served with soft naan, a hearty Pakistani breakfast.',
        ingredients: [
          '500g beef shank',
          '2 cups flour for naan',
          '1 tbsp nihari masala',
          '1/2 cup ghee',
          'Salt to taste',
          '1 onion (sliced)',
        ],
        steps: [
          'Cook beef with nihari masala, ghee, and water on low heat for 4-5 hours.',
          'Knead flour into dough, roll naan, and cook on tawa.',
          'Serve nihari hot with naan and sliced onions.',
        ],
        healthInfo: 'Calories: 450 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in iron from beef.\n- Supports energy with carbs.',
        time: '5 hours',
        rating: 4.8,
      ),
      RecipeModel(
        name: 'Chana Chaat',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 250,
        description: 'A tangy and spicy chickpea salad, a light and flavorful Pakistani breakfast.',
        ingredients: [
          '1 cup boiled chickpeas',
          '1 tomato (chopped)',
          '1 onion (chopped)',
          '1 tsp chaat masala',
          '1 tbsp lemon juice',
        ],
        steps: [
          'Mix boiled chickpeas with chopped tomato and onion.',
          'Add chaat masala and lemon juice, toss well.',
          'Serve fresh.',
        ],
        healthInfo: 'Calories: 250 kcal\nHealth Benefits:\n- High in protein and fiber.\n- Rich in vitamins from veggies.\n- Supports digestion.',
        time: '10 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Anda Paratha',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 300,
        description: 'A stuffed paratha with spiced eggs, a protein-packed Pakistani breakfast.',
        ingredients: [
          '2 cups whole wheat flour',
          '2 eggs',
          '1 tsp red chili powder',
          '1 tbsp ghee',
          'Salt to taste',
        ],
        steps: [
          'Knead flour into dough, rest for 20 minutes.',
          'Scramble eggs with chili powder and salt.',
          'Stuff egg mixture in rolled dough, cook with ghee on tawa.',
          'Serve hot.',
        ],
        healthInfo: 'Calories: 300 kcal\nHealth Benefits:\n- High in protein from eggs.\n- Rich in carbs for energy.\n- Supports muscle growth.',
        time: '20 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Lassi with Paratha',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 320,
        description: 'A refreshing yogurt drink paired with flaky paratha for a balanced breakfast.',
        ingredients: [
          '1 cup yogurt',
          '1 tbsp sugar',
          '2 cups flour',
          '1 tbsp ghee',
          'Water as needed',
        ],
        steps: [
          'Blend yogurt with sugar and water to make lassi.',
          'Knead flour into dough, roll parathas, and cook with ghee.',
          'Serve lassi with hot parathas.',
        ],
        healthInfo: 'Calories: 320 kcal\nHealth Benefits:\n- Rich in probiotics for gut health.\n- High in carbs for energy.\n- Hydrating and refreshing.',
        time: '15 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Siri Paye',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 400,
        description: 'A traditional Pakistani dish with slow-cooked trotters, perfect for a hearty breakfast.',
        ingredients: [
          '500g goat trotters',
          '1 tbsp ginger-garlic paste',
          '1 tsp red chili powder',
          '1/2 cup ghee',
          'Salt to taste',
        ],
        steps: [
          'Cook trotters with ginger-garlic paste, chili, and water on low heat for 6 hours.',
          'Add ghee and salt, simmer for 30 minutes.',
          'Serve hot with naan or bread.',
        ],
        healthInfo: 'Calories: 400 kcal\nHealth Benefits:\n- High in collagen for joint health.\n- Rich in protein for muscle repair.\n- Warm and nourishing.',
        time: '6.5 hours',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Oatmeal with Fresh Fruits',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 200,
        description: 'A warm, fiber-rich breakfast with oats and seasonal fruits for a healthy start.',
        ingredients: [
          '1/2 cup oats',
          '1 cup mixed fruits (berries, banana)',
          '1 tbsp honey',
          '1 cup milk',
        ],
        steps: [
          'Boil milk and add oats, cook for 5 minutes.',
          'Stir in honey and top with fresh fruits.',
          'Serve warm.',
        ],
        healthInfo: 'Calories: 200 kcal\nHealth Benefits:\n- High in fiber for digestion.\n- Rich in antioxidants from fruits.\n- Provides sustained energy.',
        time: '10 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Greek Yogurt Parfait',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 250,
        description: 'A creamy, protein-packed breakfast with yogurt, granola, and berries.',
        ingredients: [
          '1 cup Greek yogurt',
          '1/4 cup granola',
          '1/2 cup mixed berries',
          '1 tsp honey',
        ],
        steps: [
          'Layer yogurt in a glass.',
          'Add granola and berries alternately.',
          'Drizzle honey on top and serve.',
        ],
        healthInfo: 'Calories: 250 kcal\nHealth Benefits:\n- Rich in probiotics for gut health.\n- High in protein for muscle strength.\n- Low in fat.',
        time: '5 min',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Avocado Toast',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 220,
        description: 'A simple, healthy breakfast with creamy avocado on whole-grain bread.',
        ingredients: [
          '1 slice whole-grain bread',
          '1/2 avocado',
          'Pinch of salt',
          '1 tsp lemon juice',
        ],
        steps: [
          'Toast the bread until golden.',
          'Mash avocado with salt and lemon juice.',
          'Spread on toast and serve.',
        ],
        healthInfo: 'Calories: 220 kcal\nHealth Benefits:\n- High in healthy fats for heart health.\n- Rich in fiber for digestion.\n- Low in carbs.',
        time: '5 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Scrambled Eggs with Spinach',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 180,
        description: 'A protein-rich breakfast with fluffy eggs and nutritious spinach.',
        ingredients: [
          '2 eggs',
          '1 cup spinach',
          '1 tbsp olive oil',
          'Salt and pepper to taste',
        ],
        steps: [
          'Heat oil and sauté spinach for 2 minutes.',
          'Whisk eggs and pour into pan.',
          'Scramble until cooked, season, and serve.',
        ],
        healthInfo: 'Calories: 180 kcal\nHealth Benefits:\n- High in protein for energy.\n- Rich in iron for blood health.\n- Low in calories.',
        time: '10 min',
        rating: 4.4,
      ),
      RecipeModel(
        name: 'Smoothie Bowl',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 230,
        description: 'A vibrant, refreshing breakfast with blended fruits and healthy toppings.',
        ingredients: [
          '1 banana',
          '1/2 cup berries',
          '1/2 cup yogurt',
          '1 tbsp chia seeds',
        ],
        steps: [
          'Blend banana, berries, and yogurt until smooth.',
          'Pour into a bowl and sprinkle chia seeds.',
          'Serve cold.',
        ],
        healthInfo: 'Calories: 230 kcal\nHealth Benefits:\n- Packed with vitamins for immunity.\n- Rich in omega-3s for heart health.\n- High in antioxidants.',
        time: '5 min',
        rating: 4.8,
      ),
      RecipeModel(
        name: 'Pancakes with Maple Syrup',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 300,
        description: 'Fluffy pancakes with a touch of natural sweetness for a delightful breakfast.',
        ingredients: [
          '1 cup flour',
          '1 egg',
          '1 cup milk',
          '2 tbsp maple syrup',
          '1 tsp baking powder',
        ],
        steps: [
          'Mix flour, egg, milk, and baking powder into batter.',
          'Cook batter in a pan until golden on both sides.',
          'Drizzle maple syrup and serve.',
        ],
        healthInfo: 'Calories: 300 kcal\nHealth Benefits:\n- Provides quick energy.\n- Low in unhealthy fats.\n- Balanced with natural sugars.',
        time: '15 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Whole-Grain Toast with Peanut Butter',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 250,
        description: 'A filling breakfast with nutty peanut butter on whole-grain bread.',
        ingredients: [
          '1 slice whole-grain bread',
          '2 tbsp peanut butter',
          '1 tsp honey',
        ],
        steps: [
          'Toast the bread until crisp.',
          'Spread peanut butter evenly.',
          'Drizzle honey and serve.',
        ],
        healthInfo: 'Calories: 250 kcal\nHealth Benefits:\n- High in protein for energy.\n- Rich in healthy fats for heart health.\n- Supports muscle growth.',
        time: '5 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Chia Seed Pudding',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 200,
        description: 'A creamy, nutrient-dense pudding made with chia seeds for a light breakfast.',
        ingredients: [
          '3 tbsp chia seeds',
          '1 cup almond milk',
          '1 tsp vanilla',
          '1 tbsp fruit topping',
        ],
        steps: [
          'Mix chia seeds with almond milk and vanilla.',
          'Let it sit for 2 hours or overnight.',
          'Add fruit topping and serve.',
        ],
        healthInfo: 'Calories: 200 kcal\nHealth Benefits:\n- Rich in omega-3s for brain health.\n- High in fiber for digestion.\n- Low in calories.',
        time: '10 min',
        rating: 4.4,
      ),
      RecipeModel(
        name: 'Breakfast Burrito',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 280,
        description: 'A savory wrap with eggs, veggies, and cheese for a hearty morning meal.',
        ingredients: [
          '1 tortilla',
          '2 eggs',
          '1/2 cup bell peppers',
          '2 tbsp cheese',
          '1 tsp salsa',
        ],
        steps: [
          'Scramble eggs with bell peppers.',
          'Place mixture on tortilla with cheese and salsa.',
          'Roll and serve warm.',
        ],
        healthInfo: 'Calories: 280 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in vitamins for immunity.\n- Balanced with healthy fats.',
        time: '10 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Fruit and Nut Muesli',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 240,
        description: 'A crunchy mix of oats, nuts, and dried fruits for a wholesome breakfast.',
        ingredients: [
          '1/2 cup muesli',
          '1/4 cup mixed nuts',
          '1/2 cup yogurt',
          '1 tsp honey',
        ],
        steps: [
          'Mix muesli and nuts with yogurt.',
          'Drizzle honey on top.',
          'Serve fresh.',
        ],
        healthInfo: 'Calories: 240 kcal\nHealth Benefits:\n- High in fiber for digestion.\n- Rich in antioxidants for wellness.\n- Provides sustained energy.',
        time: '5 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Egg Omelette with Tomatoes',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 180,
        description: 'A light and flavorful omelette with fresh tomatoes for a quick breakfast.',
        ingredients: [
          '2 eggs',
          '1 tomato (chopped)',
          '1 tbsp olive oil',
          'Salt and pepper to taste',
        ],
        steps: [
          'Whisk eggs with salt and pepper.',
          'Heat oil, add chopped tomatoes, and pour eggs.',
          'Cook until set, fold, and serve.',
        ],
        healthInfo: 'Calories: 180 kcal\nHealth Benefits:\n- High in protein for energy.\n- Rich in vitamins from tomatoes.\n- Low in calories.',
        time: '8 min',
        rating: 4.4,
      ),
      RecipeModel(
        name: 'French Toast with Honey',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 300,
        description: 'A sweet and crispy toast soaked in egg mixture, served with honey.',
        ingredients: [
          '2 slices bread',
          '1 egg',
          '1/2 cup milk',
          '2 tbsp honey',
          '1 tsp cinnamon',
        ],
        steps: [
          'Whisk egg, milk, and cinnamon.',
          'Dip bread slices and cook on a pan until golden.',
          'Drizzle honey and serve warm.',
        ],
        healthInfo: 'Calories: 300 kcal\nHealth Benefits:\n- Provides quick energy.\n- Rich in calcium from milk.\n- Low in unhealthy fats.',
        time: '10 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Cornflakes with Milk',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 220,
        description: 'A quick and crunchy breakfast with cornflakes and cold milk.',
        ingredients: [
          '1 cup cornflakes',
          '1 cup milk',
          '1 tbsp sugar',
          '1/2 cup sliced banana',
        ],
        steps: [
          'Pour cornflakes into a bowl.',
          'Add milk, sugar, and sliced banana.',
          'Serve immediately.',
        ],
        healthInfo: 'Calories: 220 kcal\nHealth Benefits:\n- Rich in vitamins from fortified cornflakes.\n- Provides quick energy.\n- Low in fat.',
        time: '3 min',
        rating: 4.3,
      ),
    ],
  )
  // Add more categories here



,


  ///===========================================>>>> Lunch FOOD

  CategoryModel(
    title: 'Lunch',
    image: 'https://www.tastingtable.com/img/gallery/20-traditional-pakistani-dishes-everyone-needs-to-try-once/intro-1674666910.webp',
    recipes: [
      RecipeModel(
        name: 'Gourmet Quinoa Bowl',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 250,
        description: 'A nutritious bowl with quinoa and roasted vegetables, perfect for a light lunch.',
        ingredients: [
          '1 cup quinoa',
          '2 cups mixed vegetables (bell peppers, zucchini, carrots, etc.)',
          '2 tablespoons olive oil',
          'Salt and pepper to taste',
          '1 tablespoon lemon juice',
          'Fresh herbs (parsley or basil) for garnish',
        ],
        steps: [
          'Preheat the oven to 400°F (200°C). Toss the mixed vegetables with olive oil, salt, and pepper, then spread them on a baking sheet and roast for 20-25 minutes until tender.',
          'Meanwhile, rinse the quinoa under cold water, then cook it according to package instructions. Once cooked, fluff with a fork and mix in the roasted vegetables and lemon juice. Garnish with fresh herbs before serving.',
        ],
        healthInfo: 'Calories: 250 kcal\nHealth Benefits:\n- High in protein and fiber.\n- Rich in vitamins from vegetables.\n- Supports digestion.',
        time: '30 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Chicken Karahi',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 400,
        description: 'A spicy Pakistani dish with tender chicken cooked in a rich tomato-based curry.',
        ingredients: [
          '500g chicken',
          '2 tomatoes (chopped)',
          '1 tbsp ginger-garlic paste',
          '1 tsp red chili powder',
          '1/2 cup oil',
          'Salt to taste',
        ],
        steps: [
          'Heat oil in a pan, add ginger-garlic paste and sauté for 2 minutes.',
          'Add chicken, tomatoes, chili powder, and salt, cook until tender.',
          'Simmer for 10 minutes, serve hot with naan.',
        ],
        healthInfo: 'Calories: 400 kcal\nHealth Benefits:\n- High in protein from chicken.\n- Rich in lycopene from tomatoes.\n- Boosts metabolism.',
        time: '40 min',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Biryani',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 450,
        description: 'A fragrant rice dish with spiced meat or vegetables, a Pakistani lunch favorite.',
        ingredients: [
          '2 cups basmati rice',
          '500g chicken or mutton',
          '1 tbsp biryani masala',
          '1/2 cup yogurt',
          '1/4 cup oil',
        ],
        steps: [
          'Marinate meat with yogurt and biryani masala for 1 hour.',
          'Cook rice halfway, layer with marinated meat, and steam for 20 minutes.',
          'Serve hot with raita.',
        ],
        healthInfo: 'Calories: 450 kcal\nHealth Benefits:\n- Rich in protein and carbs.\n- Provides energy from rice.\n- Supports muscle health.',
        time: '1.5 hours',
        rating: 4.8,
      ),
      RecipeModel(
        name: 'Dal and Roti',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 300,
        description: 'A simple and wholesome lunch with lentil curry and whole wheat flatbread.',
        ingredients: [
          '1 cup lentils (dal)',
          '2 cups flour',
          '1 tsp turmeric',
          '1 tbsp ghee',
          'Salt to taste',
        ],
        steps: [
          'Cook lentils with turmeric and salt until soft.',
          'Knead flour into dough, roll roti, and cook on tawa with ghee.',
          'Serve dal hot with roti.',
        ],
        healthInfo: 'Calories: 300 kcal\nHealth Benefits:\n- High in protein and fiber.\n- Rich in iron from lentils.\n- Supports digestion.',
        time: '30 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Grilled Chicken Salad',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 280,
        description: 'A fresh and light lunch with grilled chicken and crisp vegetables.',
        ingredients: [
          '200g chicken breast',
          '1 cup lettuce',
          '1 tomato (sliced)',
          '1 tbsp olive oil',
          'Salt and pepper to taste',
        ],
        steps: [
          'Grill chicken with salt, pepper, and olive oil for 10 minutes.',
          'Toss lettuce and tomato in a bowl.',
          'Add grilled chicken on top and serve.',
        ],
        healthInfo: 'Calories: 280 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in vitamins from veggies.\n- Low in carbs.',
        time: '15 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Pulao with Raita',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 380,
        description: 'A flavorful rice dish with vegetables or meat, served with cooling yogurt sauce.',
        ingredients: [
          '2 cups basmati rice',
          '1 cup mixed vegetables',
          '1 tsp cumin seeds',
          '1/2 cup yogurt',
          '2 tbsp oil',
        ],
        steps: [
          'Sauté cumin seeds and vegetables in oil.',
          'Add rice and water, cook until done.',
          'Serve with yogurt mixed with salt and spices.',
        ],
        healthInfo: 'Calories: 380 kcal\nHealth Benefits:\n- Rich in carbs for energy.\n- High in probiotics from raita.\n- Balanced with veggies.',
        time: '30 min',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Fish Curry with Rice',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 350,
        description: 'A spicy fish curry served with steamed rice, a coastal Pakistani lunch.',
        ingredients: [
          '300g fish fillets',
          '1 cup rice',
          '1 tbsp curry powder',
          '1/2 cup coconut milk',
          'Salt to taste',
        ],
        steps: [
          'Cook rice with water until fluffy.',
          'Simmer fish with curry powder and coconut milk for 15 minutes.',
          'Serve hot with rice.',
        ],
        healthInfo: 'Calories: 350 kcal\nHealth Benefits:\n- High in omega-3s from fish.\n- Rich in protein for muscle health.\n- Supports heart health.',
        time: '25 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Vegetable Stir-Fry with Naan',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 320,
        description: 'A quick stir-fry of mixed vegetables served with soft naan bread.',
        ingredients: [
          '2 cups mixed vegetables',
          '2 cups flour for naan',
          '1 tbsp soy sauce',
          '1 tbsp oil',
          'Salt to taste',
        ],
        steps: [
          'Stir-fry vegetables with oil and soy sauce for 10 minutes.',
          'Knead flour into dough, roll naan, and cook on tawa.',
          'Serve vegetables with hot naan.',
        ],
        healthInfo: 'Calories: 320 kcal\nHealth Benefits:\n- Rich in vitamins from veggies.\n- High in fiber for digestion.\n- Low in fat.',
        time: '20 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Beef Keema with Paratha',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 400,
        description: 'A spiced minced beef dish paired with flaky paratha for a hearty lunch.',
        ingredients: [
          '300g minced beef',
          '2 cups whole wheat flour',
          '1 tsp garam masala',
          '1 tbsp ghee',
          'Salt to taste',
        ],
        steps: [
          'Cook beef with garam masala and salt until dry.',
          'Knead flour into dough, roll parathas, and cook with ghee.',
          'Serve keema with hot parathas.',
        ],
        healthInfo: 'Calories: 400 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in iron from beef.\n- Supports energy.',
        time: '35 min',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Lentil Soup with Bread',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 280,
        description: 'A warm and nutritious lentil soup served with crusty bread.',
        ingredients: [
          '1 cup lentils',
          '1 slice bread',
          '1 tsp cumin',
          '1 tbsp olive oil',
          'Salt to taste',
        ],
        steps: [
          'Cook lentils with cumin, oil, and salt until soft.',
          'Blend into a smooth soup, simmer for 5 minutes.',
          'Serve hot with bread on the side.',
        ],
        healthInfo: 'Calories: 280 kcal\nHealth Benefits:\n- High in protein and fiber.\n- Rich in iron for blood health.\n- Supports digestion.',
        time: '25 min',
        rating: 4.4,
      ),
      RecipeModel(
        name: 'Chicken Biryani',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 420,
        description: 'Aromatic rice cooked with spiced chicken, a flavorful Pakistani lunch.',
        ingredients: [
          '2 cups basmati rice',
          '500g chicken',
          '1 tbsp biryani masala',
          '1/2 cup yogurt',
          '1/4 cup oil',
        ],
        steps: [
          'Marinate chicken with yogurt and biryani masala for 1 hour.',
          'Cook rice halfway, layer with chicken, and steam for 20 minutes.',
          'Serve with raita or salad.',
        ],
        healthInfo: 'Calories: 420 kcal\nHealth Benefits:\n- High in protein from chicken.\n- Rich in carbs for energy.\n- Balanced with spices.',
        time: '1.5 hours',
        rating: 4.8,
      ),
      RecipeModel(
        name: 'Saag with Makki di Roti',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 340,
        description: 'A traditional Punjabi dish with mustard greens and cornmeal flatbread.',
        ingredients: [
          '2 cups mustard greens',
          '1 cup cornmeal',
          '1 tbsp ghee',
          '1 tsp garlic paste',
          'Salt to taste',
        ],
        steps: [
          'Cook greens with garlic paste and salt until soft.',
          'Knead cornmeal into dough, roll roti, and cook with ghee.',
          'Serve saag hot with roti.',
        ],
        healthInfo: 'Calories: 340 kcal\nHealth Benefits:\n- Rich in vitamins from greens.\n- High in fiber for digestion.\n- Supports eye health.',
        time: '30 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Pasta with Veggies',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 320,
        description: 'A colorful pasta dish with sautéed vegetables in a light sauce.',
        ingredients: [
          '1 cup pasta',
          '1 cup mixed vegetables',
          '1 tbsp olive oil',
          '1 tsp Italian seasoning',
          'Salt to taste',
        ],
        steps: [
          'Cook pasta according to package instructions.',
          'Sauté vegetables with oil and seasoning for 10 minutes.',
          'Mix with pasta and serve warm.',
        ],
        healthInfo: 'Calories: 320 kcal\nHealth Benefits:\n- Rich in carbs for energy.\n- High in vitamins from veggies.\n- Low in fat.',
        time: '20 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Mutton Korma',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 450,
        description: 'A rich and creamy mutton curry cooked with aromatic spices.',
        ingredients: [
          '500g mutton',
          '1 cup yogurt',
          '1 tbsp garam masala',
          '1/2 cup oil',
          'Salt to taste',
        ],
        steps: [
          'Marinate mutton with yogurt and garam masala for 2 hours.',
          'Cook with oil and water on low heat for 1 hour.',
          'Serve hot with rice or naan.',
        ],
        healthInfo: 'Calories: 450 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in iron from mutton.\n- Supports energy.',
        time: '1.5 hours',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Cucumber and Tomato Salad',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 150,
        description: 'A refreshing and light salad with crisp cucumbers and juicy tomatoes.',
        ingredients: [
          '1 cucumber (sliced)',
          '2 tomatoes (chopped)',
          '1 tbsp olive oil',
          '1 tsp lemon juice',
          'Salt to taste',
        ],
        steps: [
          'Mix cucumber and tomatoes in a bowl.',
          'Drizzle with olive oil and lemon juice, add salt.',
          'Serve fresh.',
        ],
        healthInfo: 'Calories: 150 kcal\nHealth Benefits:\n- Rich in vitamins from veggies.\n- High in water content for hydration.\n- Low in calories.',
        time: '5 min',
        rating: 4.4,
      ),
      RecipeModel(
        name: 'Chicken Wrap',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 300,
        description: 'A tasty wrap with grilled chicken, veggies, and a creamy sauce.',
        ingredients: [
          '1 tortilla',
          '200g grilled chicken',
          '1/2 cup lettuce',
          '1 tbsp mayo',
          'Salt to taste',
        ],
        steps: [
          'Grill chicken with salt until cooked.',
          'Spread mayo on tortilla, add chicken and lettuce.',
          'Roll and serve.',
        ],
        healthInfo: 'Calories: 300 kcal\nHealth Benefits:\n- High in protein from chicken.\n- Rich in vitamins from veggies.\n- Supports energy.',
        time: '15 min',
        rating: 4.6,
      ),
      RecipeModel(
        name: 'Aloo Gosht',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 380,
        description: 'A hearty Pakistani dish with tender mutton and potatoes in a spiced gravy.',
        ingredients: [
          '500g mutton',
          '2 potatoes (cubed)',
          '1 tbsp ginger-garlic paste',
          '1 tsp red chili powder',
          '1/2 cup oil',
        ],
        steps: [
          'Cook mutton with ginger-garlic paste, chili, and water for 1 hour.',
          'Add potatoes, simmer for 20 minutes until tender.',
          'Serve with rice or naan.',
        ],
        healthInfo: 'Calories: 380 kcal\nHealth Benefits:\n- High in protein from mutton.\n- Rich in carbs from potatoes.\n- Supports muscle health.',
        time: '1.5 hours',
        rating: 4.7,
      ),
      RecipeModel(
        name: 'Vegetable Fried Rice',
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
        kcal: 310,
        description: 'A quick and tasty rice dish with stir-fried vegetables and soy sauce.',
        ingredients: [
          '2 cups cooked rice',
          '1 cup mixed vegetables',
          '1 tbsp soy sauce',
          '1 tbsp oil',
          'Salt to taste',
        ],
        steps: [
          'Heat oil, stir-fry vegetables for 5 minutes.',
          'Add rice and soy sauce, mix well for 5 minutes.',
          'Serve hot.',
        ],
        healthInfo: 'Calories: 310 kcal\nHealth Benefits:\n- Rich in carbs for energy.\n- High in vitamins from veggies.\n- Low in fat.',
        time: '15 min',
        rating: 4.5,
      ),
      RecipeModel(
        name: 'Lamb Roast',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        kcal: 420,
        description: 'A succulent roasted lamb with aromatic spices, perfect for a special lunch.',
        ingredients: [
          '500g lamb',
          '1 tbsp garam masala',
          '1/2 cup yogurt',
          '2 tbsp oil',
          'Salt to taste',
        ],
        steps: [
          'Marinate lamb with yogurt, garam masala, and salt for 2 hours.',
          'Roast in oven at 375°F (190°C) for 1 hour.',
          'Serve with rice or bread.',
        ],
        healthInfo: 'Calories: 420 kcal\nHealth Benefits:\n- High in protein for muscle health.\n- Rich in iron from lamb.\n- Supports energy.',
        time: '2 hours',
        rating: 4.8,
      ),
      RecipeModel(
        name: 'Spinach Rice',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        kcal: 290,
        description: 'A healthy rice dish with fresh spinach and mild spices.',
        ingredients: [
          '2 cups cooked rice',
          '1 cup spinach (chopped)',
          '1 tsp cumin seeds',
          '1 tbsp oil',
          'Salt to taste',
        ],
        steps: [
          'Heat oil, add cumin seeds and spinach, cook for 5 minutes.',
          'Mix in cooked rice and salt, stir for 5 minutes.',
          'Serve warm.',
        ],
        healthInfo: 'Calories: 290 kcal\nHealth Benefits:\n- Rich in iron from spinach.\n- High in fiber for digestion.\n- Supports blood health.',
        time: '15 min',
        rating: 4.6,
      ),
    ],
  )
]; 